extends:
  - standard
  - plugin:import/recommended
  - plugin:import/typescript # this line does the trick

plugins:
  - import
  - promise
  - standard
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
  ecmaVersion: 6

rules:
  comma-dangle: off
  "import/no-unused-modules": [1, {"unusedExports": true}]
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": ["error"]
